### ISSUE TITLE
Add support for collapsing.

### ISSUE THREAD

**Issue by Klockchops** [justint/usd-idea#8]
Can you please add support for collapsing?

**Comment by justint** [comment]
Hey @Klockchops, code folding is implemented in the plug-in via the [USDFoldingBuilder](https://github.com/justint/usd-idea/blob/master/src/main/java/com/justint/usdidea/codeinsight/folding/USDFoldingBuilder.java). It should allow folding of any metadata blocks (parentheses) and any prim/dictionary bodies (brackets).

If the folding isn't available in a file, it may be because the parser errored while trying to read it. Are there any language errors highlighted in your file?
